const categories = [
  {
    id: 1,
    title: "C/C++",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis nisi sed turpis vulputate viverra. Morbi ligula elit, hendrerit non nisl tincidunt, sodales consequat magna.",
    img: "icons8-c-programming.svg",
    imgBig: "IoT.jpg",
  },
  {
    id: 2,
    title: "HTML",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis nisi sed turpis vulputate viverra. Morbi ligula elit, hendrerit non nisl tincidunt, sodales consequat magna.",
    img: "icons8-html-5.svg",
    imgBig: "CIMG0593.JPG",
  },
  {
    id: 3,
    title: "CSS",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis nisi sed turpis vulputate viverra. Morbi ligula elit, hendrerit non nisl tincidunt, sodales consequat magna.",
    img: "icons8-css-logo.svg",
    imgBig: "PLC.jpg",
  },
  {
    id: 4,
    title: "Circuit Analysis",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis nisi sed turpis vulputate viverra. Morbi ligula elit, hendrerit non nisl tincidunt, sodales consequat magna.",
    img: "CircuitAnalysis.webp",
    imgBig: "Micro.jpg",
  },
  {
    id: 5,
    title: "System Design",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis nisi sed turpis vulputate viverra. Morbi ligula elit, hendrerit non nisl tincidunt, sodales consequat magna.",
    img: "proteuslogoweb.svg",
    imgBig: "Design.png",
  },
  {
    id: 6,
    title: "PCB Design",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis nisi sed turpis vulputate viverra. Morbi ligula elit, hendrerit non nisl tincidunt, sodales consequat magna.",
    img: "EasyEDALogo.svg",
    imgBig: "PCB.jpg",
  },
  {
    id: 7,
    title: "Ms. Word",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis nisi sed turpis vulputate viverra. Morbi ligula elit, hendrerit non nisl tincidunt, sodales consequat magna.",
    img: "Microsoft_Office_Word_Logo.svg",
    imgBig: "PCB.jpg",
  },
  {
    id: 8,
    title: "Ms. Excel",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis nisi sed turpis vulputate viverra. Morbi ligula elit, hendrerit non nisl tincidunt, sodales consequat magna.",
    img: "Microsoft_Office_Excel_Logo.svg",
    imgBig: "PCB.jpg",
  },
  {
    id: 9,
    title: "Figma",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis nisi sed turpis vulputate viverra. Morbi ligula elit, hendrerit non nisl tincidunt, sodales consequat magna.",
    img: "Figma-Logo-Png-Vector.svg",
    imgBig: "PCB.jpg",
  },
  {
    id: 10,
    title: "PLC",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis nisi sed turpis vulputate viverra. Morbi ligula elit, hendrerit non nisl tincidunt, sodales consequat magna.",
    img: "PLCLogo.png",
    imgBig: "PCB.jpg",
  },
  {
    id: 11,
    title: "English",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis nisi sed turpis vulputate viverra. Morbi ligula elit, hendrerit non nisl tincidunt, sodales consequat magna.",
    img: "English.png",
    imgBig: "PCB.jpg",
  },
  {
    id: 12,
    title: "Power System",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis nisi sed turpis vulputate viverra. Morbi ligula elit, hendrerit non nisl tincidunt, sodales consequat magna.",
    img: "FluidSIM.svg",
    imgBig: "PCB.jpg",
  },
];

export default categories;
